### ISSUE TITLE
Allow OrderManager.cancelOrder on already payed Orders.

### ISSUE THREAD

**Issue by paulhenke** [st-tu-dresden/salespoint#132]
We could create another `AccountancyEntry` named `CanceledProductPaymentEntry` (or something like that) and add is to the `Accountancy` if an already payed Order ist canceled.

See [https://auditorium.inf.tu-dresden.de/en/questions/3533](Cancel paid Order [Salespoint])

**Comment by odrotbohm** [comment]
Already implemented in #230.
