### ISSUE TITLE
BusinessTime needs a way to reset to current time

### ISSUE THREAD

**Issue by B4ckslash** [st-tu-dresden/salespoint#189]
BusinessTime currently has no way to reset it to current time. This would be useful so that time-sensitive integration tests (where BusinessTime is autowired) do not get broken by any other test forwarding the time.
Is there perhaps another/preferred way to resolve this problem?

**Comment by olivergierke** [comment]
That's in place by merging #194. Feel free to give the 6.4.2 snapshots a try.
