### ISSUE TITLE
Cart should always return CartItems in insertion order and shouldn't change CartItem identifiers

### ISSUE THREAD

**Issue by paulhenke** [st-tu-dresden/salespoint#191]
The current `Cart` implementation uses a `List<T>` to hold all `CartItem`s.
After an "update" (`Cart.addOrUpdateItem`) the old `CartItem` is removed and a new one is added to the end of the `List`, thus changing the initial insertion order.
I think it's easier for customers, if their cart has a stable order.

I also thinks, it's easier for devs, if the `Cartitem.id` doesn't change if the item is updated.

See https://auditorium.inf.tu-dresden.de/de/questions/3925

**Comment by pha-Z** [comment]
cartItem now does not change price when changing quantity :(
