### ISSUE TITLE
Changing quantity of a CartItem creates a new item with wrong price

### ISSUE THREAD

**Issue by pha-Z** [st-tu-dresden/salespoint#201]
the price is set on during object construction and will never change since the attribute is final

**Comment by olivergierke** [comment]
Probably a side-effect of 6bfbf1eacd30fa37f04590da3d9482bb852083ad.

**Comment by olivergierke** [comment]
Would you mind checking the latest snapshots?

**Comment by pha-Z** [comment]
Has been solved now (for us).

**Comment by olivergierke** [comment]
`6.4.2.RELEASE` has just been released in case you want to upgrade to a stable version. Announcement coming soon.
