### ISSUE TITLE
Allow to explictly disable the inventory update via property

### ISSUE THREAD

**Issue by odrotbohm** [st-tu-dresden/salespoint#253]
Introduce `salespoint.inventory.disable-updates` to completely disable the inventory update.

**Comment by martinmo** [comment]
I guess this issue should be postponed to 7.2.1.

**Comment by odrotbohm** [comment]
I decided to go with a more drastic approach by simply removing the entire bean from the application context if the property is set. Merged for 7.2.x as well as it doesn't affect existing applications.
