### ISSUE TITLE
Is Interval open or closed?

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/salespoint#255]
From a presentation today I got the feedback that it was not documented whether `Interval` represents open or closed intervals, i.e., whether the start/end is included or not. And if, how it is possible to get to the other variant. Probably also extends to `IntervalBuilder`.

**Comment by odrotbohm** [comment]
Hm, aren't that two different things? Bounded/unbounded is whether there's an upper/lower limit at all. That's orthogonal to whether the bounds are used inclusively or exclusively? `Interval` is bounded in both directions (ensured by `IntervalBuilder`) and – AFAICS – inclusive. I.e. for two `Interval`s A and B with `A.end == B.start`, all of `A.contains(A.end)`, `A.contains(B.start)`, `B.contains(A.end)` and `B.contains(B.start)` will return `true`.

I guess, we could try to move to Spring Data's [`Range`](https://github.com/spring-projects/spring-data-commons/blob/e3d80aa69ab745f22ddc0c9ba98d3f381772feae/src/main/java/org/springframework/data/domain/Range.java#L36) type that allows to be specific about all of those aspects and is also supported as repository method parameter type for `Between` queries.

**Comment by martinmo** [comment]
> I guess, we could try to move to Spring Data's Range type that allows to be specific about all of those aspects and is also supported as repository method parameter type for Between queries.

I think this is the way to go :+1: For 7.3, we should think about deprecating `Interval` and switch the framework to `Range`.

In the meantime, for 7.2, I'll document the gotchas. It's not consistent: 
- `Interval.contains()` is inclusive. This matches the semantics of the Spring Data JPA `Between` method keyword which is itself based on JPQL `BETWEEN`.
- `Interval.overlaps()` is exclusive.
- `Interval.toDuration()` and `Interval.getDuration()` exclude the end (because `Duration.between()` does it this way).
