### ISSUE TITLE
Exact Quantity.equals() comparison is inconsistent with Quantity.toString()

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/salespoint#284]
Let's say I have two `Quantity` objects `q1` and `q2`,  both with `metric == Metric.UNIT` and

* `q1.amount` equal to `new BigDecimal("1.0")`, and
* `q2.amount` equal to `new BigDecimal("1")`.

(Note that the two `BigDecimal` objects are not equal as per `BigDecimal.equals()`.)

Now I compare `q1` and `q2` using `assertThat(q1).isEqualTo(q2)`. This fails with the following error message:

```
org.opentest4j.AssertionFailedError: 
Expecting:
 <"1 (Quantity@5acf93bb)">
to be equal to:
 <"1 (Quantity@7e7be63f)">
but was not.
```

The misleading identical output of actual vs. expected is because the current `toString()` always strips trailing zeroes. (By the way, the objects are considered unequal because they use an exact comparison of `amount`, instead of `BigDecimal.compareTo()`.)

I suggest to:
* include the canonical representation of `amount` (as returned by `BigDecimal.toString()`), making it easier to spot the difference, and
* complete the `compareTo()`-like feature set of `Quantity` by adding `isEqualTo()` to the already existing `isGreaterThan()`, `isLessThan()`, etc.

Using `BigDecimal.compareTo()` instead of `BigDecimal.equals()` in `Quantity.equals()` is probably not an option because of inconsistencies with `hashCode()`.

**Comment by odrotbohm** [comment]
Are you sure you're testing a current version of Salespoint? Asking because AssertJ outputs `Quantity@5acf93bb` while we actually have a proper implementation of `toString()` formatting the value and the metric.

**Comment by odrotbohm** [comment]
Looks like AssertJ is printing the object hash in case the `toString()` representations are equal. I have a fix here that forwards the precision of the underlying `BigDecimal` to the format to be used for rendering. I'll add `isEqualTo()` as well.
