### ISSUE TITLE
Creating Quantity with double values should be deprecated

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/salespoint#285]
Internally, `Quantity` holds the `amount` in a `BigDecimal` object with arbitrary precision. However, `Quantity`s can only be created from `long`s and `double`s. The latter one can lead to subtle errors because of limited precision. For example, the following test fails:

```java
assertThat(Quantity.of(0.1 + 0.2)).isEqualTo(Quantity.of(0.1).add(Quantity.of(0.2)));
```

Because `0.1 + 0.2` is `0.30000000000000004` and not `0.3` (in FP arithmetic).

Therefore, we should mark the constructor methods that take `double`s deprecated and add methods that take a string, to restore support for precise decimal arithmetic.

**Comment by odrotbohm** [comment]
I'm not sure I see the problem with `Quantity` here. The problem stems from the – probably not so obvious – fact that you're not creating a `Quantity.of(0.3)`. That however is a problem of the addition in the first place. I think it's hard to argue why you shouldn't be able to create `Quantity` instances from rather static values, like 0,5.

The whole point of the existance of `Quantity` is to make sure that the operations actually work as you expect them to (plus making sure that only values with the same `Metric` are used in such operations).

**Comment by martinmo** [comment]
Yes, you are right :+1: Basically, it's my (or the user's) fault if I use FP arithmetic and not `Quantity` or `BigDecimal` arithmetic.

However, I still think that there could be constructors allowing to create "fractional" `Quantity`s from more precise data types or descriptions. Let's assume someone uses `Quantity.of(1.1111111111111111)`. It involves no FP calculation, but will create a `Quantity` that's represented by a `BigDecimal(1.1111111111111112)`.

Disclaimer: I admit this value will probably never be used in practice ;-) And because there are more important issues to solve I'm okay with closing this issue as `wontfix`.
