### ISSUE TITLE
SalesPoint Javadoc search is not working

### ISSUE THREAD

**Issue by phthalodale** [st-tu-dresden/salespoint#306]
You can hover above the autocompleted names of salespointpackages but clicking leads to 404 :(

**Comment by odrotbohm** [comment]
Can you elaborate? Are you talking about the JavaDoc published on the website? From within the IDE? What do you mean with "autocompleted names of Salespoint packages"?

**Comment by martinmo** [comment]
I think he means the search box in the upper right corner of <https://st.inf.tu-dresden.de/SalesPoint/api/>. For example: search for "time", click on a suggestion, and see a 404.

**Comment by martinmo** [comment]
Somehow it inserts an `undefined/` into the URL. If you remove that, the page is found.

**Comment by odrotbohm** [comment]
Interesting. Probably a glitch in our JavaDoc setup. Will investigate.

**Comment by odrotbohm** [comment]
https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url
