### ISSUE TITLE
Allow lookup of custom AccountancyEntry extensions via Accountancy

### ISSUE THREAD

**Issue by cmrschwarz** [st-tu-dresden/salespoint#314]
This issue was raised during SWP2019/20 evaluation. By request of @martinmo I'm resubmitting it here. Currently it's quite cumbersome to add custom data to `UserAccount`s and `AccountancyEntry` objects. A positive Salespoint example of a solution is the catalog package. The main `Catalog`'s interface type is: 

```java
interface Catalog<T extends Product>
```

This allows the Salespoint user to subclass Product and add all the fields they want. The additional fields are still be managed by the `Catalog` repository, and especially when you query that repository you get out objects of your subtype, not some generic `Product` instances.

In contrast, `Accountancy` and `UserAccountManager` don't allow this kind of flexibility.

Therefore I suggest changing the type of `Accountancy` to

```java
interface Accountancy<T extends AccountancyEntry> { … }
```

and of `UserAccountManager` to

```java
interface UserAccountManager<T extends UserAccount> { … }
```

which would make them much more flexible and applicable.

**Comment by odrotbohm** [comment]
I think what you suggest is fine for `Accountancy`. `UserAccount` is deliberately not designed for extension but delegation: a customer *has* an account, it is not one. All examples of additional data that folks intended to add to the `UserAccount` type have been better of in a custom domain type that's then holding a reference to the `UserAccount`.
