### ISSUE TITLE
Rework access to currently logged in UserAccount

### ISSUE THREAD

**Issue by odrotbohm** [st-tu-dresden/salespoint#337]
The current implementation of the support for `@LoggedIn` suffers from quite a few problems:

* The support for `Optional` feels over-engineered as there's hardly a use case to define a controller method that can or should be invoked with *and* without authentication.
* The `HandlerMethodArgumentResolver` implementation is not really needed as Spring Security [allows to automatically resolve](https://docs.spring.io/spring-security/site/docs/current/reference/html5/#mvc-authentication-principal) handler method arguments referring to the principal.

**Comment by martinmo** [comment]
Also see #389.
