### ISSUE TITLE
Broken dependency in 7.3.x branch (javamoney)

### ISSUE THREAD

**Issue by svenkarol** [st-tu-dresden/salespoint#346]
Hi folks, 

we discovered that there's a problem on the 7.3.x branch with a dependency to the `moneta-core 1.4-tud`. Fresh building of any project that I tried relying on that version of Salespoint and the `st-lab-parent 2.3.0` fails with an HTTP-401 Error on that dependency. 

The specific message I get is:
`BUILD-SNAPSHOT: Failed to collect dependencies at de.tudresden.inf.st:salespoint-framework:jar:7.3.0 -> org.javamoney.moneta:moneta-core:jar:1.4-tud: Failed to read artifact descriptor for org.javamoney.moneta:moneta-core:jar:1.4-tud: Could not transfer artifact org.javamoney:moneta-parent:pom:1.4-tud from/to spring-libs-milestone (https://repo.spring.io/libs-milestone): Access denied to https://repo.spring.io/libs-milestone/org/javamoney/moneta-parent/1.4-tud/moneta-parent-1.4-tud.pom. Error code 401, -> [Help 1]`

Steps to reproduce:
- clear cache in `user/.m2`
- trigger a new build, e.g., in Videoshop `./mvnw clean package`

Workaround: create a local repository for that dependency (works from command-line but not so much on Eclipse Spring Tools)

**Comment by martinmo** [comment]
Hi, that's interesting, until today I didn't know that Salespoint used a custom moneta build ;-) (my guess is that version `1.4-tud` of moneta is/was a custom moneta build which works around a behavior change as described in e99e67b70008498804c7021d6408f3114d07e257).

Your maven error message says it tried to load it from `repo.spring.io` – that's odd, I am sure that such a custom build should be found on our maven repo (under `https://st.inf.tu-dresden.de/SalesPoint/repository/`). However, the URL https://st.inf.tu-dresden.de/SalesPoint/repository/org/javamoney/moneta-parent/1.4-tud/moneta-parent-1.4-tud.pom gives a 404.

@odrotbohm do you have an idea what could be wrong?

**Comment by svenkarol** [comment]
Hi! Is there any chance to create a new release with a cherry-pick of e99e67b70008498804c7021d6408f3114d07e257 ? I did that on my fork, and it seems to fix the issue. However, two test cases fail on my local build, but they those fail on aa9fd28bbd27d18bd667d7401ed8426d244ce4e0 too.

**Comment by martinmo** [comment]
Hi, yes I'm going to try it ASAP. Because I am usually not doing the releases, there is a little chance that I mess things up 😬 I'll give my best. Btw, sorry for the delayed answer, last week I was on vacation.

**Comment by martinmo** [comment]
Interestingly, when I try to build the current clean 7.3.x branch with `mvn clean test`, Maven prints this line when downloading moneta:

```
Downloading from maven-default-http-blocker: http://0.0.0.0/org/javamoney/moneta-parent/1.4-SNAPSHOT/maven-metadata.xml
```

This seems to be a [new feature in Maven 3.8.1](https://maven.apache.org/docs/3.8.1/release-notes.html) to block externel non-https repositories by default.

**Comment by martinmo** [comment]
I have created the 7.3.1 release, but it didn't go as flawless as described in the readme 😁 The jars should be available in our repository. However, somehow the documentation on the website is still for 7.3.0, I am now trying to sort this out.

**Comment by svenkarol** [comment]
Great! Thank you very much!
