### ISSUE TITLE
Method signature leads to error for unauthenticated users

### ISSUE THREAD

**Issue by Schlossgeist** [st-tu-dresden/salespoint#389]
@GetMapping("/cart")
	@PreAuthorize("isAuthenticated()")
	String cart(Cart cart, Model model, @LoggedIn UserAccount userAccount) {
    	...
   	}

Workaround: Use `Optional<UserAccount>` as suggested by the error page

**Comment by odrotbohm** [comment]
We decided to refrain from throwing the parameter resolution exception if we find the target method to be guarded by security annotations like `@PreAuthorize`/`@Secured`.
