### ISSUE TITLE
Make it clear how to persist updated `AccountancyEntry`s

### ISSUE THREAD

**Issue by martinmo** [st-tu-dresden/salespoint#412]
In `Accountancy`, the `add(…)` method currently has two purposes: 1) adding a new entry and 2) updating/saving an existing entry. However, the latter purpose isn't clear to Salespoint framework users, neither from the method name (i.e., something like `save(…)` would be better) nor from the javadoc. The `AccountancyEntryRepository`, which has a `save(…)` method, is package private.

**Comment by odrotbohm** [comment]
`AccountancyEntry` instances are supposed to be immutable (as that's how bookkeeping works), so I guess we need to make sure we don't write any non-new entries.
